name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - "packages/neck-pose-estimator/**"
      - ".github/workflows/publish.yml"
      - "pnpm-lock.yaml"
      - ".prettierrc"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17" # Specify Node.js version
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create dummy firebase.config.ts for CI
        run: |
          echo "export default {
            apiKey: 'DUMMY_API_KEY',
            authDomain: 'DUMMY_AUTH_DOMAIN',
            projectId: 'DUMMY_PROJECT_ID',
            storageBucket: 'DUMMY_STORAGE_BUCKET',
            messagingSenderId: 'DUMMY_MESSAGING_SENDER_ID',
            appId: 'DUMMY_APP_ID',
            measurementId: 'DUMMY_MEASUREMENT_ID'
          };" > packages/neck-pose-estimator/src/firebase.config.ts

      - name: Check for API Schema Changes
        run: |
          pnpm -F "@nkmr-lab/neck-pose-estimator" openapi
          pnpm -F "@nkmr-lab/neck-pose-estimator" format
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "API schema is out of date. Please run 'pnpm -F @nkmr-lab/neck-pose-estimator openapi' and commit the changes."
            git diff
            exit 1
          fi
        env:
          API_URL: ${{ secrets.API_URL }}
          OPENAPI_PATH: ${{ secrets.OPENAPI_PATH }}

      - name: Run Lint
        run: pnpm -F "@nkmr-lab/neck-pose-estimator" lint

      - name: Run Tests
        run: pnpm -F "@nkmr-lab/neck-pose-estimator" test

      - name: Run Type Check
        run: pnpm -F "@nkmr-lab/neck-pose-estimator" typecheck

      - name: Build package
        run: pnpm -F "@nkmr-lab/neck-pose-estimator" build

      - name: Publish to GitHub Packages
        run: pnpm -F "@nkmr-lab/neck-pose-estimator" publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
